/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "hmacs256.h"
#include "aes.h"
/* Header for class com_jinxiaolu_demo_jni_JniUtil */

#ifndef _Included_com_jinxiaolu_demo_jni_JniUtil
#define _Included_com_jinxiaolu_demo_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kuaikuaiyu_demo_jni_JniUtil
 * Method:    hmas256Sign
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jinxiaolu_demo_jni_JniUtil_hmas256Sign
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_kuaikuaiyu_demo_jni_JniUtil
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jinxiaolu_demo_jni_JniUtil_encrypt
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_kuaikuaiyu_demo_jni_JniUtil
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jinxiaolu_demo_jni_JniUtil_decrypt
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
